apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eab-chart.fullname" .}}external-dns
  labels:
    {{- include "eab-chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.11.0
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=muellermatthias.org
        - --provider=azure
        - --azure-resource-group=mc_matthias_helmakskubernetespoc-cluster_centralus
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file