apiVersion: v1
kind: Secret
metadata:
  name: azure-config-file
  labels:
    {{- include "eab-chart.labels" . | nindent 4 }}
type: Opaque
stringData: { "tenantId": "__TenantId__", "subscriptionId": "__SubscriptionId__", "resourceGroup": "__ResourceGroup__",  "aadClientId": "__AadClientId__", "aadClientSecret": "__AadClientSecret__" }
