name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
  pipelines:
    - pipeline: eabwebapp-release-pip # Name of the pipeline resource
      source: 02-EABWebApp-Create-Artifacts # Name of the pipeline referenced by the pipeline resource
      trigger: true

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
  
variables:
- group: DrMuellersExampleApp-Common
- group: DrMuellersExampleApp-Backend-Secrets
- group: DrMuellersExampleApp-Backend-Production

stages:
  - stage: Production
    displayName: "Production"
    jobs:
      - deployment: "DeploymentProduction"
        environment: "DrMuellersExampleApp-WebApp-Backend"
        displayName: "Deployment Production"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Release_Steps.yaml