name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true # batch changes if true; start a new build for every push if false (default)
  branches:
    include:
      - refs/heads/master

variables:
  BuildConfiguration: "Release"

jobs:
  - job: "BuildAndTest"
    displayName: "Build and test"
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest
    steps:
      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          vstsFeed: '3c2d9c9a-d8f7-42f4-b7a3-dddf4064110a'
      - task: DrMueller2.NuGetVulnerabilityScan.NugetVulnerabilityScanTask.NugetVulnerabilityScanTask@1
        displayName: NuGet Vulnerability Scan
        inputs:
          projectPath: "Sources/**/*.csproj"
      - task: DotNetCoreCLI@2
        displayName: "Build with warnings as errors"
        inputs:
          projects: "Sources/**/*.csproj"
          arguments: '/p:TreatWarningsAsErrors="true" --configuration $(BuildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: test
          projects: "Sources/Testing/**/*Tests.csproj"
          arguments: "--configuration --configuration $(BuildConfiguration)"
  - job: "RunResharper"
    displayName: "Run ReSharper analysis"
    pool:
      name: Azure Pipelines
      # vmImage: windows-latest
      vmImage: ubuntu-latest
    steps:
      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          vstsFeed: '3c2d9c9a-d8f7-42f4-b7a3-dddf4064110a'
      - task: Cache@2
        displayName: Cache ReSharperCLT
        inputs:
          key: ResharperCLT
          path: $(Build.SourcesDirectory)/Lib/Resharper
          cacheHitVar: ReSharperCLTCacheRestored
      - task: NuGetCommand@2
        displayName: "Restore ReSharper CLT NuGet"
        inputs:
          command: custom
          arguments: "install JetBrains.ReSharper.CommandLineTools -source https://api.nuget.org/v3/index.json -OutputDirectory $(Build.SourcesDirectory)/Lib/Resharper"
        condition: ne(variables.ReSharperCLTCacheRestored, 'true')
      - task: alanwales.resharper-code-analysis.custom-build-task.ResharperCli@2
        displayName: "Run ReSharper analysis"
        inputs:
          solutionOrProjectPath: DrMuellersExampleApp.sln
          commandLineInterfacePath: $(Build.SourcesDirectory)/Lib/Resharper/JetBrains.ReSharper.CommandLineTools.2021.2.0/tools
          additionalArguments: "--no-build"
