name: 1.0$(rev:.r) # build numbering format

trigger: none # will disable CI builds entirely

variables:
  BuildConfiguration: 'Release'
  PublishPath: '$(Build.ArtifactStagingDirectory)/App'
  FinalOutputPath: '$(Build.ArtifactStagingDirectory)/ArtifactsOutput'
  AdditionalArtifactsSourceFolder: 'Pipelines_WebApp/Building/AdditionalArtifacts'

resources:
  pipelines:
    - pipeline: eabwebapp-create-artifacts-pip # Name of the pipeline resource
      source: 01-EABWebApp-Continuous-Integration # Name of the pipeline referenced by the pipeline resource
      trigger:
        branches:
          - refs/heads/master

jobs:
  - job: 'BuildAndPublishAsArtifact'
    displayName: 'Build and save zipped Artifact'
    pool:
      name: Azure Pipelines
      vmImage: windows-latest

    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore'
        inputs:
          command: restore
          projects: 'Sources/**/*.csproj'

      - task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
        displayName: gitversion/setup
        inputs:
          versionSpec: 5.x
          includePrerelease: true

      - task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
        displayName: gitversion/execute
        inputs:
          updateAssemblyInfo: true

      - task: DotNetCoreCLI@2
        displayName: Publish Web API
        inputs:
          command: publish
          publishWebProjects: false
          projects: 'Sources/Application/Mmu.DrMuellersExampleApp.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(PublishPath) /p:DeleteExistingFiles=True'
          zipAfterPublish: false
          modifyOutputPath: false

      - task: qetza.replacetokens.replacetokens-task.replacetokens@5
        displayName: 'Replace tokens in appsettings.json'
        inputs:
          rootDirectory: '$(PublishPath)'
          targetFiles: |
            **/appsettings.json
          tokenPattern: rm
          verbosity: detailed
          keepToken: true

      - task: ArchiveFiles@2
        displayName: Archive as ZIP
        inputs:
          rootFolderOrFile: '$(PublishPath)'
          includeRootFolder: false
          archiveFile: '$(FinalOutputPath)/WebApp.zip'

      - task: CopyFiles@2
        displayName: 'Copy additional artifacts'
        inputs:
          SourceFolder: '$(AdditionalArtifactsSourceFolder)'
          TargetFolder: '$(FinalOutputPath)/Artifacts'

      - task: PublishBuildArtifacts@1
        displayName: 'Save output'
        inputs:
          PathtoPublish: '$(FinalOutputPath)'
